
### Get Request
@server = http://localhost:4004
@credAdmin = Authorization: Basic ed.chavez.pe@gmail.com:

### post Books
POST {{server}}/catalog/Books
Content-Type: application/json
{{credAdmin}}

{
	
	"ID": 3,
  	"stock": 2,
  	"title": "The mask"
   
}
### post Method
POST {{server}}/catalog/Type_TX
Content-Type: application/json
{{credAdmin}}

{
	
  	"name": "prueba 12",
  	"alias": "TEST2",
	"description":"test 123",
	"usuarioRegistro":"MCHAVEZP",
	"activo":true
   
}


### get findAll
GET  {{server}}/catalog/findAPI()
Content-Type: application/json
{{credAdmin}}

### post PAY
POST {{server}}/catalog/payDetail
Content-Type: application/json
{{credAdmin}}

{
	
  	"context":{
		"id": "4cbd8d85-b48e-11ed-afa1-0242ac120002",
		"description": "prueba 12",
		"value": 40.2,
		"rxh":true,
		"details":[			
		{
		"value": 50.21,
		 "description":"base1",
		 "method": "f0e1c894-0be2-4d3b-85fb-746c8bac3429",
		 "entity1": "c95e0a94-24cd-433e-b8b3-bf06991896db",
		 "category": "c3cdce9e-91cf-4e74-bb34-ce13e38eddcf"
    	},{
         "value": 50.22,
		 "description":"base1",
		  "method": "f0e1c894-0be2-4d3b-85fb-746c8bac3429",
		 "entity1": "c95e0a94-24cd-433e-b8b3-bf06991896db",
		 "category": "c3cdce9e-91cf-4e74-bb34-ce13e38eddcf"
    	},{
         "value": 50.23,
		 "description":"base2",
		  "method": "f0e1c894-0be2-4d3b-85fb-746c8bac3429",
		 "entity1": "c95e0a94-24cd-433e-b8b3-bf06991896db",
		 "category": "c3cdce9e-91cf-4e74-bb34-ce13e38eddcf"
    	}]
		 
	}

   
}

### post Method
POST {{server}}/catalog/Flow
Content-Type: application/json
{{credAdmin}}

{
  	"name": "prueba 12",
  	"alias": "TEST2",
	"description":"test 123",
	"usuarioRegistro":"MCHAVEZP",
	"activo":true
   
}